#!/bin/bash

USER_DIR=/home/ubuntu
PW_FILE=/etc/virtuoso/dba_password
PW_CHANGED=/etc/virtuoso/password_changed

source $USER_DIR/RDFeasy/lib/myBashRc

test -e $PW_CHANGED && exit 0

wait_until virtuoso_ready
change_password `generate_dba_password`

