#!/bin/bash

logger running change_password_at_boot

USER_DIR=/home/ubuntu
PW_FILE=/etc/virtuoso/dba_password
PW_CHANGED=/etc/virtuoso/password_changed

source $USER_DIR/RDFeasy/lib/myBashRc

logger testing if pasword_changed flag is set

test -e $PW_CHANGED && exit 0

logger "password_changed flag was not; waiting for virtuoso_ready"
wait_until virtuoso_ready
logger "virtuoso_ready detected; changing password" 

change_password `generate_dba_password`

