#!/bin/bash


USER_DIR=/home/ubuntu
PW_FILE=/etc/virtuoso/dba_password
PW_CHANGED=/etc/virtuoso/password_changed

source $USER_DIR/RDFeasy/lib/myBashRc

test -e $PW_CHANGED && exit 0

logger "password_changed flag was not set;  doing first boot initialization"
warm_volume /dev/xvdf
logger "volume warmed; starting virtuoso"

update-rc.d virtuoso defaults
service virtuoso start

wait_until virtuoso_ready

logger "virtuoso_ready detected; changing password" 

change_password `generate_dba_password`

